---
kind: pipeline
name: base

platform:
  os: linux
  arch: amd64

steps:
# pre slack notification
- name: pre_slack_notification
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel: dev
    username: drone
    template: >
      {{build.link}} with build number #{{build.number}} started on <http://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}}:{{build.branch}}> by {{build.author}} due to {{build.event}}. See commit {{build.commit}}.
  when:
    event:
      include:
      - push
      exclude:
      - tag
      - pull_request
    branch:
      include:
      - main

# build dockerfile & send image to ecr
- name: publish-image
  image: plugins/ecr
  environment:
    PLUGIN_STORAGE_DRIVER: overlay2
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY
    secret_key:
      from_secret: AWS_SECRET_KEY
    repo: wishyoo-base
    region: us-west-2
    registry: 727869158831.dkr.ecr.us-west-2.amazonaws.com # <account_id>.dkr.ecr.us-east-1.amazonaws.com
    tags:
      - ${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
      - latest
  # commands:
  #   - $(aws ecr get-login --no-include-email --region us-east-1)
  when:
    event:
      include:
      - push
      exclude:
      - tag
      - pull_request
    branch:
      include:
      - main # for pull_request use main@{upstream} as it evaluates true if the pull request is to main (e.g. from develop)

# post slack notification
- name: post_slack_notification
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel: dev
    username: drone
    icon_url: https://img.stackshare.io/service/668/rShq67tG.png
    image_url: https://img.stackshare.io/service/668/rShq67tG.png
    template: >
      {{#success build.status}}
        build {{build.number}} Pipeline succeeded with commit {{build.commit}} in {{build.branch}} with build {{build.number}} generated by {{build.author}}, see the build results {{build.link}}.
      {{else}}
        build {{build.number}} Pipeline failed with commit {{build.commit}} in {{build.branch}} with build {{build.number}} generated by {{build.author}}, see the build results {{build.link}}.
      {{/success}}
  when:
    event:
      include:
      - push
      exclude:
      - tag
      - pull_request
    branch:
      include:
      - main
  trigger:
    status: [ success, failure ]
